version: '3.9'

services:
    mysql:
        image: mysql:8.0.25
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - /var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - 3306:3306
    
    postgres:
        image: postgres:13.3
        restart: always
        environment:
            POSTGRES_PASSWORD: secret
        volumes:
            - /var/lib/postgresql/data
        ports:
            - 5432:5432

